### ISSUE TITLE
Compile errors

### ISSUE THREAD

**Issue by ychdata** [Flone-dnb/SilentServer#1]
Hi,my friend,I'm happy that I can use your project.But I have a little problem.If you can give me some help, I will really appreciate you.
The main errors are saying that "no matching constrcutor for initialization of std::ifstream or std::ofstream".
MY e-mail is 1939177124@qq.com.If you can't open the photos,you can conract with me by e-mail.
![problem1](https://user-images.githubusercontent.com/68702982/88369634-0be38b80-cdc3-11ea-9329-ad3d664225f6.png)
![problem2](https://user-images.githubusercontent.com/68702982/88369636-0c7c2200-cdc3-11ea-9f17-aa6336d818d8.png)

**Comment by Flone-dnb** [comment]
It might be a compiler thing, I'm building it using MSVC 2017 x64 (and it works fine), but other compilers might mark this as an error. I recommend you using MSVC 2017 if you're not using it, but as a quick fix (may cause some problems), you may write ".c_str()" to strings.
For example:
`std::ofstream logFile (temp.c_str(), std::ios::app);`.

Tell me if the issue still exists.

**Comment by ychdata** [comment]
Thank you Flone-dnb.I'm honored to hear from you.With your help,I think my problem will be solve right away.In the future,if you have some problem,you can tell me.MY teammake and I will try our best to help you.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Flone-dnb/SilentServer"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年7月24日(星期五) 下午4:06
收件人:&nbsp;"Flone-dnb/SilentServer"<SilentServer@noreply.github.com&gt;;
抄送:&nbsp;"清晨之火"<1939177124@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [Flone-dnb/SilentServer] HI,My friend (#1)





 
It might be a compiler thing, I'm building it using MSVC 2017 x64 (and it works fine), but other compilers might mark this as an error. I recommend you using MSVC 2017 if you're not using it, but as a quick fix (may cause some problems), you may write ".c_str()" to strings.
 For example:
 std::ofstream logFile (temp.c_str(), std::ios::app);.
 
Tell me if the issue still exists.
