### ISSUE TITLE
How to find public IP

### ISSUE THREAD

**Issue by ychdata** [Flone-dnb/SilentServer#2]
Thank you again,Flone .After installing another compiler,the program can be opened right.But now I have the other problem.You can see this in the photo.
And I don't konw how my friend can join 'my room' in this program.I have done this thing in your word: "Forward TCP port 51337 (text chat) and UDP port 51337".But I don't know the meaning of this sentences: "Tell your friends your public IPv4 address."
IF the problem 3 is hard to solve,it's not a big deal.The more important thing is :  How can my friend add my ip?By the program or by Router web interface？

![problem3](https://user-images.githubusercontent.com/68702982/88399416-6a2b6100-cdf9-11ea-9271-28faf582c3a4.png)

**Comment by ychdata** [comment]
![problem3](https://user-images.githubusercontent.com/68702982/88399818-0a818580-cdfa-11ea-92c1-5bc327f29b04.png)

**Comment by Flone-dnb** [comment]
1. You can get your public IP address by googling something like "what's my IP".
2. Have you made changes to the source code? Are you using the default 51337 port (see in Chat - Settings)?

**Comment by ychdata** [comment]
Ok，but how can my friend join my room?



---Original---

**Comment by Flone-dnb** [comment]
He should use Silent (client) application and connect to your IP.
